[package]
name = "dotter"
version = "0.10.5"
authors = ["SuperCuber <amit.gold00@gmail.com>"]
description = "A dotfile manager and templater written in rust"
repository = "https://www.github.com/SuperCuber/dotter"
readme = "README.md"
keywords = ["dotter", "dotfiles", "manager"]
categories = ["command-line-utilities"]
license = "Unlicense"

[dependencies]
anyhow = "1.*"
clap = "2.*"
crossterm = "0.18.*"
diff = "0.1.*"
env_logger = "0.7.*"
handlebars = { version = "3.*", features = ["script_helper"] }
log = "0.4.*"
meval = "0.2.*"
pager = "0.16.*"
serde = "1.*"
shellexpand = "1.*"
structopt = "0.3.*"
thiserror = "1.*"
toml = "0.4.*"
watchexec = "=1.14.1"

[target.'cfg(windows)'.dependencies]
dunce = "1.*"
