[package]
name = "dotter"
version = "0.3.1"
authors = ["SuperCuber <amit.gold00@gmail.com>"]
description = "A small dotfile manager"
repository = "https://www.github.com/SuperCuber/dotter"
readme = "README.md"
keywords = ["dotter", "dotfiles", "manager"]
categories = ["command-line-utilities"]
license = "WTFPL"

[dependencies]
toml = "0.4.*"
serde = "1.0.*"
structopt = "0.3.*"
clap = "2.33.*"
env_logger = "0.7.*"
log = "0.4.*"
